name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install flavio==2.3.1
        pip install smelli==2.3.1
        pip install wilson==2.0
        pip install numpy
        pip install scipy
        pip install matplotlib
        pip install iminuit==1.3.10
        pip install pandas
        pip install PyYAML
        pip install shap
        pip install xgboost
        pip install scikit-learn
        pip install git+https://github.com/Jorge-Alda/parscanning.git@v1.0#egg=parscanning
        pip install -e git+https://github.com/Jorge-Alda/texfig.git#egg=texfig
    - name: Analysing the code with pylint
      run: |
        cd SMEFT19
        echo
        pylint --rcfile='.pylintrc' `ls -R|grep .py$|xargs`
