name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install flavio==1.5.0
        pip install smelli==1.3.1
        pip install wilson==2.0
        pip install numpy
        pip install scipy
        pip install matplotlib
        pip install iminuit
        pip install pandas
        pip install PyYAML
        pip install shap
        pip install xgboost
        pip install scikit-learn
        pip install git+https://github.com/Jorge-Alda/parscanning.git@v1.0#egg=parscanning
        pip install https://github.com/Jorge-Alda/texfig.git
    - name: Analysing the code with pylint
      run: |
        cd SMEFT19      
        pylint --disable C0103,W0312,W1401,C0301,C0326,R,C0200,C0411,W0311 `ls -R|grep .py$|xargs`
